import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const onGameClickHandler = () =>{
    window.location.href='/game'
  }
  return (
    <>
      <Head>
        <title>Machine Coding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{margin:'0px', padding:'0px'}}>
       <button className={styles.buttonClass} onClick={onGameClickHandler}>
        Want to play, Press Me!
       </button>
      </main>
    </>
  );
}
