import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import LandingPageComponent from "../components/LandingPageComponent/LandingPageComponent";
import BackButton from "../components/BackButton/BackButton";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Machine Coding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainBody}>
      <LandingPageComponent/>
      </main>
    </>
  );
}
